# a,b = map(int, input().split())
# print(a+b, a-b, sep='\n')
# a, b, c = map(int, input().split())
# print((a+b)%c, ((a%c)+(b%c))%c, (a*b)%c, ((a%c)*(b%c))%c, sep='\n')
a, b, c = map(int, input().split())
d, e, f = map(int, input().split())
